---
title: "Chronic Disease Indicators (CDI) - Data Exploration and Cleaning"
author: "Chetan, Augustine"
output: 
    html_document:
        theme: united
        highlight: tango
        code_folding: show
        fig_caption: true
        toc: true
        toc_depth: 3
        toc_float: true
        number_sections: true
        fig_width: 8
        fig_height: 6
        fig_align: "center"
        df_print: paged
        keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libraries}
# Load the required libraries
library(dplyr)
library(ggplot2)
library(tidyr)
library(readr)
```

```{r dataset}
# Load the dataset
cdi <- read.csv("us_cdi_dataset.csv", stringsAsFactors = FALSE)
```

```{r head}
# Display the first few rows of the dataset
head(cdi)
```

```{r summary_1}
# Display the Topics in the dataset
cdi %>% select(Topic) %>% distinct()
```

```{r summary_2}
# we are interested in understanding the mortality from chronic diseases
# how mortality specifically (as opposed to morbidity) is related to other variables in the dataset

# Filter for Question containing mortality
# Display the Question and Topic
cdi %>% filter(grepl("mortality", Question, ignore.case = TRUE)) %>% select(Question, Topic) %>% distinct()
```

```{r summary_3}
# Mortality from chronic diseases is a broad topic
# Focusing in on 'Mortality with end-stage renal disease' for the purpose of this analysis
# Filter for Question is 'Mortality with end-stage renal disease'

cdi_renal <- cdi %>% filter(Question == "Mortality with end-stage renal disease")
```

```{r summary_4}
# explore cdi_renal
glimpse(cdi_renal)
```

```{r summary_5}
# How many years of data do we have?
cdi_renal %>% select(YearStart, YearEnd) %>% distinct()
```

```{r summary_6}
# How many states are represented in the dataset?
cdi_renal %>% select(LocationDesc) %>% distinct() %>% count()
```

```{r summary_7}
# What are the unique values for the DataValueType, DataValueUnit
# This column contains the type of data in the dataset
cdi_renal %>% select(DataValueType, DataValueUnit) %>% distinct()
```

```{r summary_8}
# What are the unique values for the StratificationCategory1, Stratification1?
# This column contains the stratification category for the data
cdi_renal %>% select(StratificationCategory1, Stratification1) %>% distinct()
```

```{r plot_1}
# we want to aggregate by YearStart, DataValueType (filter for Crude Rate and Age-adjusted Rate) and calculate the mean DataValue
# first, lets check if there are any missing values in the DataValue column
cdi_renal %>% filter(is.na(DataValue))

# convert DataValue to numeric
cdi_renal <- cdi_renal %>% mutate(DataValue = as.numeric(DataValue))

# convert YearStart to factor for better visualization
cdi_renal <- cdi_renal %>% mutate(YearStart = as.factor(YearStart))

# aggregate by YearStart, LocationAbbr, DataValueType and calculate the mean DataValue
cdi_renal_agg <- cdi_renal %>% 
    filter(!is.na(DataValue)) %>% 
    group_by(YearStart, LocationAbbr, DataValueType) %>% 
    summarise(mean_data_value = mean(DataValue, na.rm = TRUE))

head(cdi_renal_agg)

# with LocationAbbr as rows, YearStart as columns, calculate the mean_data_value for Crude Rate and Age-adjusted Rate
cdi_renal_agg_wide <- cdi_renal_agg %>% 
    spread(YearStart, mean_data_value)

# for each DataValueType, display the mean_data_value for each state over the years
cdi_renal_agg_wide %>% 
    filter(DataValueType == "Crude Rate") %>%
    select(LocationAbbr, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`)

cdi_renal_agg_wide %>% 
    filter(DataValueType == "Age-adjusted Rate") %>%
    select(LocationAbbr, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`)
```
